version: "3"
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./../:/var/www/praetorian/current/backend/:cached
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 7501:80
    depends_on:
      - php-fpm

  php-fpm:
    build: php-fpm
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@db:3306/praetorian
    volumes:
      - ./../:/var/www/praetorian/current/backend/:cached
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:3303:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=praetorian
      - MYSQL_USER=praetorian
      - MYSQL_PASSWORD=praetorian